### ISSUE TITLE
Autocomplete : only one result is returned

### ISSUE THREAD

**Issue by shavounet** [cleverage/eav-manager#101]
With a basic autocomplete attribute :
```yaml
                product_sku:
                    type: autocomplete_data_selector
                    required: true
                    options:
                        allowed_families:
                            - Product
```

only one result is returned in autocomplete.

### Versions used

* cleverage/eav-manager                          v3.0.7
* pagerfanta/pagerfanta                          v2.1.3
* sidus/eav-bootstrap-bundle                     v2.1.5

### Debug info

- query looks correct, but something goes wrong with the pager
  * in `\Sidus\EAVBootstrapBundle\Autocomplete\ResponseRenderer::renderResponse`
  * `foreach ($pager as $data)` loops only once
  * `foreach (iterator_to_array($pager->getCurrentPageResults()) as $data)` loops as much as needed
