### ISSUE TITLE
JS issue in admin with nested embedded

### ISSUE THREAD

**Issue by shavounet** [cleverage/eav-manager#27]
**Test case**
* lastest version of the CDM
* use this kind of model setup (embedded attribute with multi values containing another embedded attribute) : 
```yaml
        OrderFulfillment:
            attributes:
                items:
                    type: embed_multi_family
                    multiple: true
                    options:
                        allowed_families:
                            - OrderFulfillmentItem

        OrderFulfillmentItem:
            attributes:
                orderItem:
                    type: embed_multi_family
                    options:
                        allowed_families:
                            - OrderItem
```

**Result**
* the second data inside "items" takes the place of the first (database is ok)
![capture d ecran 2018-04-11 a 11 52 03-fullpage](https://user-images.githubusercontent.com/2323369/38610009-e864e9d6-3d7f-11e8-8e61-cd7739da444b.png)
