### ISSUE TITLE
The base template should be configurable

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/eav-manager#46]
Actually the only way to customize the base template seems to use the Twig template overriding process. This is not very convenient  and not a very good practice.

It is more easier to have a configuration option :
```yml
# config/config.yaml
cleverage_eav_manager:
    admin:
        base_template: my_little_template.html.twig
# ...
```
