### ISSUE TITLE
Error when adding a date range filter

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/eav-manager#72]
When adding a date range filter, an error occurred when using this filter :
```
Cannot read index "startDate" while trying to traverse path "[startDate]". Available indices are "Array
```

The config is the following :
```yaml
sidus_admin:
    configurations:
        publication:
            controller_pattern:
                - 'CleverAge\EAVManager\AdminBundle\Action\EAV\{{Action}}Action'
            template_pattern:
                - '@CleverAgeEAVManagerAdmin/EAVData/{{action}}.{{format}}.twig'
                - '@CleverAgeEAVManagerAdmin/Base/{{action}}.{{format}}.twig'
            entity: '%sidus_data_class%'
            prefix: /publication
            form_type: '%eav_form.type%'
            actions:
                list:
                    path: /{familyCode}/list
                create:
                    path: /{familyCode}/create
                read:
                    path: /{familyCode}/read/{id}
                edit:
                    path: /{familyCode}/edit/{id}
                delete:
                    path: /{familyCode}/delete/{id}
            options:
                icon: database
                families:
                    Publication: ~

sidus_data_grid:
    configurations:
        Publication:
            query_handler:
                provider: sidus.eav
                options:
                    family: Publication
                sortable:
                    - id
                    - type
                    - scriptaId
                    - title
                    - subTitle
                    - creationDate
                    - publicationDate
                filters:
                    type:
                        type: choice
                        form_options:
                            choices:
                                article.academic: ACA
                    title: ~
                    author:
                        attributes: [publishedPublications.author]
                        type: author_list
                        form_options:
                            choice_label: lastName
                            allowed_families:
                                - Author
                    scriptaId:
                        form_options:
                            label: admin.filter.scripta_id
                    creationDate:
                        type: date_range
            
            columns:
                id:
                    label: "#"
                type: ~
                scriptaId: ~
                title:
                    template: '%clickable.template%'
                subTitle: ~
                authors:
                    template: publication/list/_authors.html.twig
                creationDate: ~
                publicationDate: ~
                actions:
                    template: publication/list/_actions.html.twig
            
            actions:
                create: '%create.button%'
            
            reset_button:
                attr:
                    data-target-element: '#tg_center'
```
